### ISSUE TITLE
CI Github Actions

### ISSUE THREAD

**Issue by lzung** [UBC-MDS/colourpickr#30]
Ensure the following changes are complete:
- [x] Add continuous integration workflow
  - [x] Add both workflows (https://github.ubc.ca/MDS-2022-23/DSCI_524_collab-sw-dev_students/tree/master/files_github_actions_R)
  - [x] Ensure that all tests are passing
  - [x] Ensure that results are sent to codecov.io (`usethis`)

- [x] Add badges to the README (ci-cd, codecov, docs)

**Comment by ataciuk** [comment]
Don't need the 'docs' badge (that was for the 'read the docs' for python.  Testing to see if I can get it to show up on codecov
