### ISSUE TITLE
License and package review request (R)

### ISSUE THREAD

**Issue by lzung** [UBC-MDS/colourpickr#32]
Ensure that the following changes are complete:
- [x] Examine the license and decide whether it should be changed
- [x] Discuss reasons for the license choice in issues
- [x] Link to the Python issue if the discussion is on that repository
- [x] Initiate a review request by opening an issue using the [template](https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/A-submit-software-for-review.md) (https://github.com/UBC-MDS/software-review-2023)

**Comment by shaunhutch** [comment]
Finished the package review request here: [Issue](https://github.com/UBC-MDS/software-review-2023/issues/30)

**Comment by shaunhutch** [comment]
Discuss reasons for the license choice in issues here: [Issue](https://github.com/UBC-MDS/colourpycker/issues/43)
